---
- hosts: jboss_host

  vars_files:
    - vars/main.yml

  vars: 
    jboss_admin_user: jboss
    jboss_admin_pwd: jboss00

    jboss_app_user: user
    jboss_app_pwd : user00
  tasks:

    #Cria usuários do sistema
    - name: create jboss admin user {{jboss_admin_user}}
      ansible.builtin.shell: add-user.sh {{jboss_admin_user}} {{jboss_admin_pwd}}

    - name: install apache module to jboss
      ansible.builtin.shell: add-user.sh -a {{jboss_app_user}} {{jboss_app_pwd}}