---
- hosts: jboss_host

  vars_files:
    - vars/main.yml

  vars: 
    jboss_admin_user: jboss
    jboss_admin_pwd: jboss00

    jboss_app_user: user
    jboss_app_pwd : user00

    user_name_JBOSS: jboss  #System username 

    user_home_dir_jboss: "/home/{{ user_name_JBOSS }}"

    app_dir_JBOSS: "{{ user_home_dir_jboss }}/jboss_eap"    

    # create a variable named "shell_env" that is a dictionary
    shell_env:
      PATH: "{{ lookup('ansible.builtin.env','PATH') }}:{{ app_dir_JBOSS }}/bin"
      JBOSS_HOME: "{{ app_dir_JBOSS }}"

  tasks:

    #Cria usuários do sistema
    # - name: create jboss admin user {{jboss_admin_user}}
    #   ansible.builtin.shell: add-user.sh {{jboss_admin_user}} {{jboss_admin_pwd}}

    # - name: install jboss app user
    #   ansible.builtin.shell: add-user.sh -a {{jboss_app_user}} {{jboss_app_pwd}}

    # - name: configure data source
    #   ansible.builtin.script: jboss-cli.sh -c --file=./config-db/db-cli

    # - name: Run a script using an executable in a non-system path
    #   ansible.builtin.script: ./config-db/db-cli
    #   args:
    #     executable: jboss-cli.sh -c --file=./config-db/db-cli   

    - name: put shell var into ansible var
      set_fact:
        env_path: "{{ lookup('env','PATH') }}"
      become: yes       
      #become_user: "{{ user_name_JBOSS }}"
      #environment: "{{ shell_env }}"  #variables PATH & JBOSS_HOME           

    # print environment PATH
    - name: print $PATH
      debug: 
        msg: PATH={{ env_path }}
      become: true
      #become_user: "{{ user_name_JBOSS }}"        

    - name: put shell var into ansible var
      set_fact:
        env_jboss_home: "{{ lookup('env','JBOSS_HOME') }}"
      become: true        
      #become_user: "{{ user_name_JBOSS }}"
      #environment: "{{ shell_env }}"  #variables PATH & JBOSS_HOME           

    - name: print $JBOSS_HOME
      debug: 
        msg: JBOSS_HOME={{ env_jboss_home }}
      become: true        
      #become_user: "{{ user_name_JBOSS }}"        

    - name: print shell_env
      debug: 
        msg: shell_env={{ shell_env }}
      become: true        
      #become_user: "{{ user_name_JBOSS }}"      

    #---------------------------------------------

    - name: Copy/Transfer the scripts to hosts
      ansible.builtin.copy: 
        src: ./config/       
        dest: /home/jboss/config-jboss/
        mode: 0775
      become: true
      become_user: "{{ user_name_JBOSS }}"        

    - name: execute 'jboss-config.sh' script on hosts
      ansible.builtin.shell:
      args:
        chdir: /home/jboss/config-jboss/
        cmd: ./jboss-config.sh 
      become: true
      become_user: "{{ user_name_JBOSS }}"
      environment: "{{ shell_env }}"  #variables PATH & JBOSS_HOME           