version: "1"
name: base
services:
  #AVOID THIS COMPOSE, use docker-run-*.sh (inside base_master), it is better for use case: run, stop, remove
  ansible-apache-install:
    image: ansible_base_master:latest
    privileged: true
    volumes:
      - ~/.ssh:/root/.ssh
      - ./base_master/ansible-apache-install:/ansible
    command: sh ansible-apache-install.sh
    networks: 
      - ansible-net    
networks:
  ansible-net:
    driver: bridge
    name: ansible-net
    external: true
