version: "3"
name: master
services:
  # The services are also available by 'docker-run' alternatives in the same folder, ex.: docker-run-apache-install.sh

  jboss-install:
    build: ./base_master
    image: ansible_base_master:latest
    privileged: true
    volumes:
      - ~/.ssh/master_ssh_key_pair/:/root/.ssh/
      - ./base_master/ansible-1-jboss-install:/ansible
      - type: bind
        # variável definida no arquivo .env
        source: $ANSIBLE_LOCAL_DIR
        target: /root/.ansible/
    networks: 
      - ansible-net       
    command: ["/bin/sh","-c","./ansible-playbook.sh"]  

#external, created by 01_hosts/docker-compose.yml
networks:
  ansible-net:
    driver: bridge
    name: ansible-net
    external: true