version: "1"
name: master
services:
  # The services are also available by 'docker-run' alternatives in the same folder, ex.: docker-run-apache-install.sh

  apache-install:
    build: ./base_master
    image: ansible_base_master:latest
    privileged: true
    volumes:
      - ~/.ssh/master_ssh_key_pair/:/root/.ssh/
      - ./base_master/ansible-1-apache-install:/ansible
    networks: 
      - ansible-net       
    command: ["/bin/sh","-c","./ansible-playbook.sh"]

  apache-deploy:
    image: ansible_base_master:latest
    depends_on: 
      apache-install:
        condition: service_completed_successfully
    privileged: true
    volumes:
      - ~/.ssh/master_ssh_key_pair/:/root/.ssh/
      - ./base_master/ansible-2-apache-deploy:/ansible
    command: sh ansible-playbook.sh
    networks: 
      - ansible-net    

networks:
  ansible-net:
    driver: bridge
    name: ansible-net
    external: true