version: "3"
name: master
services:
  # The services are also available by 'docker-run' alternatives in the same folder, ex.: docker-run-apache-install.sh

  pg-install:
    image: ansible_base_master:latest
    build: ./base_master
    privileged: true
    volumes:
      - /tmp/.ansible-tmp/master_ssh_key_pair/:/root/.ssh/
      - /tmp/.ansible-tmp/:/root/.ansible/
      - ./base_master/ansible-1-pg-install:/workdir/
    networks: 
      - ansible-net       
    command: ["/bin/sh","-c","./ansible-playbook.sh"]

  jboss-install:
    image: ansible_base_master:latest
    depends_on:
      pg-install:
        #condition: service_started
        condition: service_completed_successfully
    privileged: true
    volumes:
      - /tmp/.ansible-tmp/master_ssh_key_pair/:/root/.ssh/
      - /tmp/.ansible-tmp/:/root/.ansible/
      - ./base_master/ansible-2-jboss-install:/workdir
    networks: 
      - ansible-net       
    command: ["/bin/sh","-c","./ansible-playbook.sh"]  

  jboss-config:
    image: ansible_base_master:latest
    depends_on:
      jboss-install:
        condition: service_completed_successfully
    privileged: true
    volumes:
      - /tmp/.ansible-tmp/master_ssh_key_pair/:/root/.ssh/
      - /tmp/.ansible-tmp/:/root/.ansible/
      - ./base_master/ansible-3-jboss-config:/workdir
    networks: 
      - ansible-net       
    command: ["/bin/sh","-c","./ansible-playbook.sh"]  

#external, created by 01_hosts/docker-compose.yml
networks:
  ansible-net:
    driver: bridge
    name: ansible-net
    external: true