version: "1"
name: master
services:

  apache-install:
    build: ./base_master
    image: ansible_base_master:latest
    privileged: true
    volumes:
      - ~/.ssh:/root/.ssh
      - ./base_master/ansible-apache-install:/ansible
    networks: 
      - ansible-net       
    command: ["/bin/sh","-c","./ansible-apache-install.sh"]

  apache-deploy:
    image: ansible_base_master:latest
    depends_on: 
      apache-install:
        condition: service_completed_successfully
    privileged: true
    volumes:
      - ~/.ssh:/root/.ssh
      - ./base_master/ansible-apache-deploy:/ansible
    command: sh ansible-apache-deploy.sh
    networks: 
      - ansible-net    

networks:
  ansible-net:
    driver: bridge
    name: ansible-net
    external: true