---
- hosts: web_hosts
  tasks:
    - name: extractor presents
      ansible.builtin.yum:
        name:
          - tar
          - unzip
          # - openssh-clients
        state: present
      become: true

    - name: delete extract_dir
      file: 
        path: ~/tmp/extract_dir
        state: absent
    - name: recreates extract_dir
      file: 
        path: ~/tmp/extract_dir
        state: directory   

    - name: extract archive
      unarchive:
        # remote_src: true
        # src: https://www.sourcecodester.com/sites/default/files/download/razormist/chess-game-using-javascript.zip
        src: chess-game-using-javascript.zip
        dest: ~/tmp/extract_dir
        list_files: true
        validate_certs: true
      register: response_output
    - debug:
        var: response_output
    - name: creates root directory
      file: 
        path: /var/www/root_chess_localhost
        state: directory        
    - name: sync 'extract_dir/top_dir' with 'vhost_dir/chess'
      synchronize:
        src: ~/tmp/extract_dir/{{response_output.files[0]}}
        dest: /var/www/root_chess_localhost/chess
      delegate_to: "{{ inventory_hostname }}"