---
- hosts: web_hosts

  vars:
    ansible_shell_allow_world_readable_temp: true 

    user_name: apache

    user_home_dir: "/home/{{ user_name }}"
    extract_dir: "{{ user_home_dir }}/tmp/extract_dir/"
    app_dir: "{{ user_home_dir }}/vhosts_root/chess/"

    # app_archive: "https://www.sourcecodester.com/sites/default/files/download/razormist/chess-game-using-javascript.zip"
    app_archive: "chess-game-using-javascript.zip"
    is_remote_archive: false

  tasks:
    # extractor will be used to extract files, role deploy-app-extracted
    - name: extractor presents
      ansible.builtin.yum:
        name:
          - tar
          - unzip
        state: present
      become: true
      environment: "{{ proxy_env }}"

    # rsync will be used to copy files, role deploy-app-extracted
    - name: install the latest version of rsync
      yum:
        name: rsync
        state: latest
      become: true
      environment: "{{ proxy_env }}"

    # run as apache user (sudo -u user command)
    - name: Deploy app to apache role
      import_role:
        name: deploy-app-extracted
      become: true
      become_user: "{{ user_name }}"