version: "1"
name: base
services:

  http-serve_jboss:
    build: ./base_http_serve
    image: http_serve
    container_name: serve.jboss.localhost
    volumes:
      - ~/Downloads/jboss/:/serve/
    ports:
      - 8088:8000
    networks: 
      - ansible-net

  http-serve_postgres:
    image: http_serve
    container_name: serve.postgres.localhost
    volumes:
      - ~/Downloads/postgres/:/serve/
    ports:
      - 8089:8001
    networks: 
      - ansible-net

  keypair: 
    build: ./base_keypair
    image: shared_key_pair
    volumes:
      - ~/.ssh/master_ssh_key_pair/:/work_dir/shared_key_pair/
    networks: 
      - ansible-net

  jboss-host: 
    build: ./base_host
    image: target_host

    depends_on: 
      # http-serve:
      #   condition: service_started    
      keypair:
        condition: service_completed_successfully    
    privileged: true
    volumes:
      - ~/.ssh/master_ssh_key_pair/id_ed25519.pub:/root/.ssh/authorized_keys
    networks: 
      - ansible-net

#ipam - IP Address Management Driver
#configuration to avoid conflict with VPN, when it is on
#to avoid error: "could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"
networks:
  ansible-net:
    name: ansible-net
    driver: bridge
    ipam:
      config:
        - subnet: '172.25.25.0/24'
