version: "3"
name: base
services:

  keypair: 
    build: ./base_keypair
    image: shared_key_pair
    volumes:
      - ~/.ssh/master_ssh_key_pair/:/work_dir/shared_key_pair/
    networks: 
      - ansible-net

  #vault
  hashi_vault.local:
    build: ./vault
    image: hashi_vault
    container_name: vault.local
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config/:/work_dir
    networks: 
      - ansible-net
    command: ./run.sh

  pg-host: 
    build: ./base_host
    image: target_host
    depends_on: 
      # http-serve:
      #   condition: service_started    
      keypair:
        condition: service_completed_successfully    
    privileged: true
    volumes:
      - ~/.ssh/master_ssh_key_pair/id_ed25519.pub:/root/.ssh/authorized_keys
    networks: 
      - ansible-net

  # serve jboss download folder, with zipfile
  # aquired from
  # https://developers.redhat.com/products/eap/download
  http-serve-jboss:
    build: ./base_http_serve
    image: http_serve
    container_name: serve.jboss.localhost
    volumes:
      - ~/Downloads/jboss/:/serve/
    ports:
      - 8088:8000
    networks: 
      - ansible-net

  #download postgres driver
  postgres-module:
    build: ./postgres_module
    image: get_postgres_module
    volumes: 
      - ~/tmp/Downloads/jboss-eap:/tmp/Downloads/jboss-eap
      - ./postgres_module/scripts/:/scripts
    command: sh module-config.sh
    networks: 
      - ansible-net 
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  # serve jboss postgres module
  http-serve-pg-driver:
    image: http_serve
    depends_on:
      postgres-module:
        condition: service_completed_successfully    
    container_name: serve.pg-driver.localhost
    volumes:
      - ~/tmp/Downloads/jboss-eap/:/serve/
    ports:
      - 8089:8000
    networks: 
      - ansible-net
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.xxx.rule=Host(`serve.pg-driver.localhost`)"
    #   - "traefik.docker.network=ansible-net"
    #   - "traefik.http.services.xxx.loadbalancer.server.port=8089"

  jboss-host:
    # build: ./base_host
    image: target_host
    depends_on: 
      # http-serve:
      #   condition: service_started    
      keypair:
        condition: service_completed_successfully    
    privileged: true
    deploy:
      replicas: 3    
    volumes:
      - ~/.ssh/master_ssh_key_pair/id_ed25519.pub:/root/.ssh/authorized_keys
    networks: 
      - ansible-net

#ipam - IP Address Management Driver
#configuration to avoid conflict with VPN, when it is on
#to avoid error: "could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"
networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.25.0/24
    name: ansible-net