version: "3"
name: base
services:

  keypair: 
    build: ./base_keypair
    image: shared_key_pair
    volumes:
      - /tmp/.ansible-tmp/master_ssh_key_pair/:/work_dir/shared_key_pair/
    networks: 
      - ansible-net

  web-host: 
    build: ./base_host
    image: target_host
    depends_on: 
      keypair:
        condition: service_completed_successfully    
    privileged: true
    deploy:
      replicas: 2
    volumes:
      - /tmp/.ansible-tmp/master_ssh_key_pair/id_ed25519.pub:/root/.ssh/authorized_keys
    networks: 
      - ansible-net

#ipam - IP Address Management Driver
#configuration to avoid conflict with VPN, when it is on
#to avoid error: "could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"
networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.25.0/24
    name: ansible-net
