version: "1"
name: base
services:

  web-host: 
    build: ./base_host
    image: target_host
    privileged: true
    deploy:
      replicas: 2
    volumes:
      - ~/.ssh/id_ed25519.pub:/root/.ssh/authorized_keys
    command: chown root:root /root/.ssh/authorized_keys
    networks: 
      - ansible-net

networks:
  ansible-net:
    name: ansible-net
    driver: bridge