---
- name: create user and group
  hosts: web_hosts
  gather_facts: false
  become: yes

  vars:
    s_user: 'apache'
    s_group: 'apache'
    user_password: 'apache123'

  tasks:
    - name: Get user info
      getent:
        database: passwd
        key: "{{ s_user }}"
        fail_key: no    

    - name: Get group info
      getent:
        database: group
        key: "{{ s_group }}"
        fail_key: no    

    - name: Create group apache
      ansible.builtin.group:
        name: apache
        state: present
      # when: group_check.rc != 0
      when: (ansible_facts.getent_group[s_group] | type_debug) != 'NoneType'      

    - name: Create user s_user
      ansible.builtin.user:
        name: "{{ s_user }}"
        group: "{{ s_group }}"
        state: present
        password: "{{ user_password | password_hash('sha512') }}"
      when: (ansible_facts.getent_passwd[s_user] | type_debug) != 'NoneType'


      # COPIAR O AUTHORIZED_KEYS do usuário root