#refs: 
# https://rischmann.fr/blog/setting-up-postgresql-with-ansible
# https://www.postgresql.org/download/linux/redhat/

#pg version choosed: 13

---
- hosts: pg_host

  vars_files:
    - vars/vault.yml
    - vars/main.yml

  environment: "{{ proxy_env }}"  #proxy for download openjdk

  handlers:
    - name: Restart postgresql
      ansible.builtin.service:
        name: postgresql-13
        state: restarted

  tasks:
    - name: Install PostgreSQL and psycopg2
      ansible.builtin.yum:
        name:
          - postgresql13-server
          - python3-psycopg2          
        state: present
        update_cache: true

    - name: Create the cluster
      ansible.builtin.command:
        cmd: postgresql-13-setup initdb
        creates: /var/lib/pgsql/13/data/PG_VERSION

    - name: Start and enable the service
      ansible.builtin.service:
        name: postgresql-13
        state: started
        enabled: yes
    #------------------------------------------
    - name: Set options
      community.postgresql.postgresql_set:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_options }}"
      notify:
        - Restart postgresql
    #------------------------------------------
    - name: Create the databases
      community.postgresql.postgresql_db:
        name: "{{ item }}"
        encoding: "UTF-8"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_databases }}"

    - name: Create the users
      community.postgresql.postgresql_user:
        db: "{{ item.db }}"
        name: "{{ item.name }}"
        password: "{{ item.password | default(omit) }}"
      become: true
      become_user: postgres
      environment:
        PGOPTIONS: "-c password_encryption=scram-sha-256"
      with_items: "{{ postgresql_users }}"

    - name: Create the schemas
      community.postgresql.postgresql_schema:
        db: "{{ item.db }}"
        name: "{{ item.name }}"
        owner: "{{ item.name }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_schemas }}"
    #------------------------------------------
    #This is enough for the users 'user0' and 'user1' to have complete control of the db1 and db2 databases respectively
    - name: Set the user privileges
      community.postgresql.postgresql_privs:
        database: "{{ item.db }}"
        state: present
        objs: "{{ item.objs | default(omit) }}"
        privs: "{{ item.privs }}"
        type: "{{ item.type | default(omit) }}"
        roles: "{{ item.roles | default(omit) }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_privs | default([]) }}"      
    #------------------------------------------
    - name: Add entries to pg_hba
      community.postgresql.postgresql_pg_hba:
        dest: "/var/lib/pgsql/13/data/pg_hba.conf"
        address: "{{ item.address | default(omit) }}"
        contype: "{{ item.contype }}"
        databases: "{{ item.databases }}"
        method: "{{ item.method }}"
        users: "{{ item.users }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_hba_entries }}"
      notify:
        - Restart postgresql
    #------------------------------------------        