---
- hosts: all

  tasks:

  - name: Creating multiple files
    ansible.builtin.shell: |
      echo "I am file 1"
      echo "I am file 2"
      echo "I am file 3"
      exit 1
    become: true
    register: results
    ignore_errors: true
    no_log: true

  - name: Show result with line breaks
    ansible.builtin.debug:
      var: results.stdout_lines

  - name: Fail in case of error
    ansible.builtin.fail:
    when: results is failed

    

