## DYNAMIC CONFIGURATION

http:
  routers:
    route-to-local-ip:
      rule: "Host(`web.localhost`,`chess.localhost`)"
      service: route-to-web-host

  services:
    route-to-web-host:
      loadBalancer:
        servers:
          - url: "http://base-web-host-1:80"
          - url: "http://base-web-host-2:80"