---
- hosts: jboss_host

  vars_files:
    - vars/main.yml

  vars: 
    user_name_JBOSS: jboss  #System username 

    user_home_dir_jboss: "/home/{{ user_name_JBOSS }}"

    app_dir_JBOSS: "{{ user_home_dir_jboss }}/jboss_eap"    

    # create a variable named "shell_env" that is a dictionary
    shell_env:
      PATH: "{{ lookup('ansible.builtin.env','PATH') }}:{{ app_dir_JBOSS }}/bin"
      JBOSS_HOME: "{{ app_dir_JBOSS }}"

  tasks:

    - name: Copy/Transfer the scripts to hosts
      ansible.builtin.copy: 
        src: ./start/       
        dest: /home/jboss/start-jboss/
        mode: 0775
      become: true        
      become_user: "{{ user_name_JBOSS }}"        

    - name: execute 'jboss-start.sh' script on hosts
      ansible.builtin.shell:
      args:
        chdir: /home/jboss/start-jboss/
        cmd: nohup ./jboss-start.sh 
      become: true
      become_user: "{{ user_name_JBOSS }}"
      environment: "{{ shell_env }}"  #variables PATH & JBOSS_HOME           