---

#apache user
ansible_shell_allow_world_readable_temp: true 
user_name: apache
group_name: apache
user_password: apache123

# list of users for create-users role
users:
  - {
      os_user_name: "{{ user_name }}", os_group_name: "{{ group_name }}", os_user_password: "{{ user_password }}"
    }

user_home_dir: "/home/{{ user_name }}"
app_dir: "{{ user_home_dir }}/vhosts_root/chess/"

#geerlingguy.apache
apache_vhosts:
  - {servername: "web.localhost", documentroot: "/var/www/html/"}  
  - {servername: "chess.localhost", documentroot: "{{ app_dir }}"}

# create a variable named "proxy_env" that is a dictionary
proxy_env:
  http_proxy: "{{lookup('ansible.builtin.env','HTTP_PROXY')}}"
  https_proxy: "{{lookup('ansible.builtin.env','HTTPS_PROXY')}}"

#"{{lookup('ansible.builtin.env','HTTP_PROXY')}}"  resolvs to http://172.17.0.1:5865 