---
- hosts: web_hosts

  vars:
    ansible_shell_allow_world_readable_temp: true 
    apache_user_name: apache
    apache_group_name: apache
    apache_user_password: apache123
    
    users:
      - {user_name: "{{ apache_user_name }}", 
         group_name: "{{ apache_group_name }}", 
         user_password: "{{ apache_user_password }}"
        }  

    user_home_dir: "/home/{{ apache_user_name }}"
    extract_dir: "{{ user_home_dir }}/tmp/extract_dir"
    app_home_dir: "{{ user_home_dir }}/root_chess_localhost/chess"

  tasks:
    - name: extractor presents
      ansible.builtin.yum:
        name:
          - tar
          - unzip
        state: present
      become: true

    # rsync will be used to copy files - deploy web application
    - name: install the latest version of rsync
      yum:
        name: rsync
        state: latest
      become: true      

    - name: Create user
      import_role:
        name: create-user
      become: true

    - name: creates target root directory, "{{ app_home_dir }}"
      file: 
        path: "{{ app_home_dir }}"
        state:  directory
        recurse: yes
      become: true
      become_user: apache 

    # extract to temporary dir
    - name: remove previous 'extract_dir'
      file: 
        path: "{{ extract_dir }}"
        state: absent
      become: true
      become_user: apache

    - name: recreates 'extract_dir'
      file: 
        path: "{{ extract_dir }}"
        state: directory
        recurse: yes  
      become: true
      become_user: apache          

    - name: extract archive to 'extract_dir'
      unarchive:
        # remote_src: true
        # src: https://www.sourcecodester.com/sites/default/files/download/razormist/chess-game-using-javascript.zip
        src: chess-game-using-javascript.zip
        dest: "{{ extract_dir }}"
        mode: u=rwx,g=rx,o=x
        list_files: true
        validate_certs: true
      become: true
      become_user: apache         
      register: response_output
    - debug:
        var: response_output

    # using rsync to copy to 'vhost_dir/chess'
    # synchronize: Expect that dest=~/x will be ~<remote_user>/x even if using sudo.
    - name: sync (copy) 'extract_dir/top_dir' to 'vhost_dir/chess'
      synchronize:
        src: "{{ extract_dir }}/{{response_output.files[0]}}"
        dest: "{{ app_home_dir }}"
      delegate_to: "{{ inventory_hostname }}"
      become: true
      become_user: apache 
      register: response_output
    - debug:
        var: response_output
