---
- hosts: localhost
  vars:
    ansible_become_pass: "{{ pass }}"
  tasks:
    - name: extractor presents
      ansible.builtin.yum:
        name:
          - tar
          - unzip
        state: present
        use_backend: yum
      become: true

    - name: extract archive
      unarchive:
        src: https://www.sourcecodester.com/sites/default/files/download/razormist/chess-game-using-javascript.zip
        dest: ~/tmp/extract_dir
        remote_src: true
        list_files: true
        validate_certs: true
      register: response_output
    - debug:
        var: response_output